### ISSUE TITLE
Haxe in Rio #1: vamos conhecer os Haxers do Rio?

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/haxe-in-rio#1]
Fuçando o Twitter e o GitHub vi que não pareço ser o único aqui a conhecer o Haxe.

Vamos organizar um encontro para conhecer o pessoal?

@diegomachado  
@gabrielmoreira  
@guifes  
@hemersonvianna  
@hugogrochau  
@leodutra  
@panoramix360  
@phowat  
@RafaelOliveira  
@raphaklaus  
@RonaldoSetzer  
@sdiasbernardo  
@vinicius-stutz

_peço desculpas se incluí alguém por engano ... I'm sorry if I mistakenly mentioned someone_

**Comment by guifes** [comment]
Sou a favor :)

**Comment by RafaelOliveira** [comment]
Sou a favor tb! Eu sou de Cabo Frio, mas posso ver um jeito de ir ao Rio.

**Comment by leodutra** [comment]
Tem um tempão que não uso hax...e. :smile: 
Pensei que estava até em processo de morte.
Legal.

**Comment by frenetic** [comment]
Eu dou meu apoio moral e minhas energias positivas.
É meio difícil para mim conseguir ir para o Rio de Janeiro...

**Comment by raphaklaus** [comment]
Desculpe, não sei do que se trata. Pode passar um link de referência/como achou meu link?

**Comment by jonasmalacofilho** [comment]
@frenetic onde você está? Estou combinando de encontrar com o @waneck em São Paulo no começo de agosto...

**Comment by jonasmalacofilho** [comment]
@raphaklaus sorry about that!

---

explicando...

procurei por `rio de janeiro haxe site:github.com` e filtrei rapidamente os resultados

no seu caso, devo ter batido o olho nos seus starred repos e pensado que você poderia saber da existência do Haxe e ter algum interesse em conhecer mais sobre sobre o assunto

de novo, peço desculpas

**Comment by leodutra** [comment]
Acabou pegando só quem tem "Rio de Janeiro"...
Por coincidência usei o Haxe uma época.

Mas ultimamente tenho estado mais focado no universo Java, JavaScript, Kotlin, Rust e C.
Belo ecossistema o do Haxe, mas não encontrei vagas relevantes de job com a plataforma no Rio ou SP. Vocês trabalham fora?

**Comment by RonaldoSetzer** [comment]
E ae tranquilidade, eu pilho esse econtro da galera mesmo os que nao usam mais, pois da para trocar uma idea sobre tecnologias em geral, no meu ponto de vista Haxe funciona mais pra Indie, sempre vejo projetos em Haxe nessas Jams, mas na realidade brasileira para empregos praticamente todo mundo ta indo pro mesmo barco que e JavaScript/TypeScript.

Acho que vou ate pegar para rever alguma coisa de Haxe tambem, ja to bastante enferrujado ^^
quem quizer trocar uma ideia pode me adicionar no skype: Ronaldo.Setzer

**Comment by frenetic** [comment]
@jonasmalacofilho to em Recife.

Descobri essa thread por causa do weekly do skial bainn.
Sou a favor que role esse encontro. Mesmo que eu não vá 😦 
Pq, acredito, a partir de um encontro como esse, pode ser que passemos a ter uma comunidade BR HUE HUE de Haxe.

**Comment by frenetic** [comment]
Cc: https://github.com/Tiago-Ling (@tiago-ling)

**Comment by Tiago-Ling** [comment]
Opa, legal! Estou aqui em Curitiba com o @waneck 

Por aqui estamos começando a organizar uns encontros com um pessoal que usa Haxe também! 

Sobre encontro no Rio, dependendo da data e dos compromissos, gostaria de participar! Uma ótima desculpa para dar uma passeada também, hahaha! 😄

**Comment by jonasmalacofilho** [comment]
@leodutra, @RonaldoSetzer

Ainda não é comum, ainda mais por aqui.

Acho que comecei a usar Haxe no trabalho em 2010, mas apesar de essencial para o que eu tinha que fazer – processar grandes volumes dados, construir modelos de simulação, analisar os resultados – programar estava bem embaixo (se tanto) na minha lista de atribuições; usar o Haxe foi uma iniciativa (um pouco rebelde) minha.

Atualmente, na @protocubo, uso o Haxe muito no backend (Neko, Node.js), em frontends web (JS também) e para outras ferramentas (Neko, Node.js, Java e alguns outros targets)...

**Comment by RafaelOliveira** [comment]
Eu trabalho como freelancer. Já tive uma oportunidade em que poderia usar Haxe, mas escolhi o PHP pq o cliente não teria programadores em Haxe pra continuar o projeto depois. E o trabalho teria sido mais fácil em Haxe.

Atualmente eu uso Haxe pra desenvolver games para web mobile. E eu creio (mas espero que não), que eu sou o único programador Haxe em Cabo Frio rs.

**Comment by fullofcaffeine** [comment]
Opa galera, não vivo mais no Brasil mas estou de visita. Ando aqui por Icaraí, Niterói. Quem sabe rola! Fico até dia 2/ago. Abs.

**Comment by frenetic** [comment]
Vocês, galera do Rio, poderiam se organizar para fazer o evento no próximo fim de semana, visto que o @fullofcaffeine não poderia mais depois.

Partindo desse princípio, gostaria de deixar a ideia de transformarmos isso tudo aqui, numa comunidade virtual (haxe brasil). A gente poderia utilizar essa comunidade para trocar contatos, informações sobre haxe, cursos, treinamentos, blog posts e afins.
Tem muita gente topzeira usando Haxe aqui e isso iria atrair olhares de novatos.

**Comment by jonasmalacofilho** [comment]
O fim de semana do dia 29 é ótimo para mim!  Vamos combinar no domingo?  Quem mais pode nessa data?

E que lugar vocês sugerem? _(estou no Rio há menos de 3 meses)_

**Comment by jonasmalacofilho** [comment]
@frenetic : também pensei nisso, mas não sei se já renomeio esse repo para haxe-in-brasil ou assumo que vamos (eventualmente) migrar para uma plataforma mais apropriada.

Aliás, para quem não sabe, existe um grupo no Google há algum tempo: [Haxe Brasil](https://groups.google.com/forum/#!forum/haxebr).
